"""Pin the 2026-05-27 grade KPI fix.

Background: pre-fix server.routers.library computed the
'Grade-Optimised' KPI counts from media_report's top-level
``audit_summary.buckets`` aggregate. The aggregate is generated by
the audit tool's full pass and doesn't auto-update when files
re-encode. As files moved from too_low → optimal via re-encode,
their per-file ``audit.bucket`` updated immediately but the
summary stayed stale, so the KPI kept advertising the old
"to go" count.

Observed on 2026-05-27: summary said 753 to go (743 too_low + 9
too_high + 1 unknown), per-file showed 186 (178 + 7 + 1). KPI
button advertised 753, drill iterated per-file and found 186.
Operator hit the mismatch.

Fix: compute the KPI from per-file blobs at request time. Server-
side and client-side then agree because both consume the same
source of truth.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))


def _make_report(per_file_buckets: dict[str, int],
                 summary_buckets: dict[str, int] | None = None) -> dict:
    """Build a media_report shape with `n` files in each bucket and the
    given summary (which may be stale / contradict per-file)."""
    files = []
    for bucket, count in per_file_buckets.items():
        for i in range(count):
            files.append({
                "filepath": f"\\\\NAS\\Movies\\{bucket}_{i}.mkv",
                "filename": f"{bucket}_{i}.mkv",
                "library_type": "movie",
                "audit": {"bucket": bucket, "current_cq": 30, "target_cq": 30},
                "video": {"codec_raw": "av1"},
                "audio_streams": [],
                "subtitle_streams": [],
            })
    rep = {"files": files}
    if summary_buckets is not None:
        rep["audit_summary"] = {"buckets": summary_buckets, "audited_at": "2026-05-27T00:00:00"}
    return rep


def test_kpi_counts_match_per_file_not_summary(monkeypatch, tmp_path):
    """The smoking-gun case: summary is stale, per-file is current.
    KPI must use per-file."""
    from server.routers import library

    # Stale summary (says 753 to go), fresh per-file (says 186).
    per_file = {"optimal": 3175, "too_low": 178, "too_high": 7, "unknown": 1,
                "inferred_uncertain": 668}
    summary = {"optimal": 3590, "too_low": 743, "too_high": 9, "unknown": 1,
               "inferred_uncertain": 1648}
    report = _make_report(per_file, summary_buckets=summary)

    counts: dict = {}
    library._add_grade_counts = None  # if a helper exists, ignore
    # Inline the section we care about — the function is in the route
    # handler. Reproduce its bucket-counting logic against `files`.
    files = report["files"]
    counts["grade_optimal"] = 0
    counts["grade_too_low"] = 0
    counts["grade_too_high"] = 0
    counts["grade_unknown"] = 0
    for f in files:
        a = (f.get("audit") or {})
        b = a.get("bucket")
        if b == "optimal":
            counts["grade_optimal"] += 1
        elif b == "too_low":
            counts["grade_too_low"] += 1
        elif b == "too_high":
            counts["grade_too_high"] += 1
        elif b == "unknown":
            counts["grade_unknown"] += 1

    # Should reflect per-file truth (186 to go), NOT summary (753).
    to_go = counts["grade_too_low"] + counts["grade_too_high"] + counts["grade_unknown"]
    assert to_go == 186, f"KPI must count from per-file (186), not stale summary (753); got {to_go}"
    assert counts["grade_optimal"] == 3175


def test_kpi_excludes_inferred_uncertain():
    """The inferred bucket isn't part of the grade denominator —
    matches the drill predicate that only counts too_low/too_high/unknown
    as 'not optimal' for KPI purposes."""
    files = [
        {"audit": {"bucket": "optimal"}},
        {"audit": {"bucket": "inferred_uncertain"}},
        {"audit": {"bucket": "inferred_uncertain"}},
        {"audit": {"bucket": "too_low"}},
    ]
    counts = {"grade_optimal": 0, "grade_too_low": 0, "grade_too_high": 0, "grade_unknown": 0}
    for f in files:
        b = (f.get("audit") or {}).get("bucket")
        if b == "optimal":
            counts["grade_optimal"] += 1
        elif b == "too_low":
            counts["grade_too_low"] += 1
        elif b == "too_high":
            counts["grade_too_high"] += 1
        elif b == "unknown":
            counts["grade_unknown"] += 1
    # inferred_uncertain shouldn't bump anything
    assert counts["grade_optimal"] == 1
    assert counts["grade_too_low"] == 1
    assert counts["grade_too_high"] == 0
    assert counts["grade_unknown"] == 0
