"""Periodic cleanup of ``.original.bak`` files left by the encoder.

The encoder's atomic-replace path keeps the pre-encode source as
``<file>.mkv.original.bak`` after a successful replace — a safety net
in case a quality issue is spotted post-replace and a manual rollback
is needed. Without housekeeping these accumulate forever; the
2026-05-03 audit found 1,144 of them eating 2.88 TB on the NAS.

Usage:

    # Default: list .bak files older than 7 days, dry-run
    uv run python -m tools.cleanup_bak

    # Lower the age threshold
    uv run python -m tools.cleanup_bak --older-than-days 3

    # Generate a PowerShell delete script (apostrophe-safe)
    uv run python -m tools.cleanup_bak --emit F:/AV1_Staging/cleanup_bak.ps1

    # No filter — every .bak (use after you've watched a fresh batch
    # and confirmed quality)
    uv run python -m tools.cleanup_bak --older-than-days 0 --emit ...

Discoverable enough to run from a Scheduled Task; safe by default
(emits a script rather than deleting in-process so the user reviews
before pulling the trigger).
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import time
from pathlib import Path

from paths import NAS_MOVIES, NAS_SERIES
from tools.ps1_helpers import write_delete_script


def _enumerate_bak_files() -> list[tuple[str, int, float]]:
    """Walk Movies + Series for ``.original.bak`` files.

    Uses ``Get-ChildItem`` via PowerShell rather than ``os.walk`` because
    SMB recursive walks from CPython are markedly slower than the Windows
    file-API path PowerShell uses. Returns ``[(path, size_bytes, mtime), …]``.
    """
    bases = [str(NAS_MOVIES), str(NAS_SERIES)]
    cmd = [
        "powershell", "-NoProfile", "-Command",
        "$bases = @('"
        + "','".join(b.replace("'", "''") for b in bases)
        + "'); foreach ($b in $bases) { Get-ChildItem $b -Recurse -File "
        "-Filter '*.original.bak' -ErrorAction SilentlyContinue | "
        "ForEach-Object { \"$($_.FullName)$($_.Length)$([int][double]::Parse(($_.LastWriteTime.ToFileTime() / 1e7).ToString()))\" } }",
    ]
    result = subprocess.run(
        cmd, capture_output=True, text=True, timeout=600, encoding="utf-8", errors="replace"
    )
    files: list[tuple[str, int, float]] = []
    for line in result.stdout.splitlines():
        parts = line.split("")
        if len(parts) != 3:
            continue
        try:
            files.append((parts[0], int(parts[1]), float(parts[2])))
        except ValueError:
            continue
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description="List or emit a deletion script for .original.bak files.")
    parser.add_argument(
        "--older-than-days", type=float, default=7,
        help="Only target files older than this (default: 7). Pass 0 for everything.",
    )
    parser.add_argument(
        "--emit", default=None,
        help="Write a PowerShell deletion script to this path (apostrophe-safe).",
    )
    args = parser.parse_args()

    print("Enumerating .original.bak files (this scans NAS Movies + Series)...")
    files = _enumerate_bak_files()
    if not files:
        print("No .original.bak files found.")
        return 0

    # Windows FILETIME → Unix epoch
    now = time.time()
    cutoff = now - args.older_than_days * 86400 if args.older_than_days > 0 else now + 1
    targets = [(p, sz) for p, sz, mt in files if mt < cutoff]

    total_n = len(files)
    total_size = sum(sz for _, sz, _ in files)
    target_n = len(targets)
    target_size = sum(sz for _, sz in targets)

    print(f"Total .original.bak: {total_n} files = {total_size / 1024**4:.2f} TB")
    if args.older_than_days > 0:
        print(f"Older than {args.older_than_days} days: {target_n} files = {target_size / 1024**4:.2f} TB")
    else:
        print(f"All matching (no age filter): {target_n} files = {target_size / 1024**4:.2f} TB")

    if not target_n:
        print("Nothing to do.")
        return 0

    if args.emit:
        out = Path(args.emit)
        size = write_delete_script(
            [p for p, _ in targets],
            str(out),
            header=(
                f"# Auto-generated by tools.cleanup_bak. "
                f"Deletes {target_n} .original.bak file(s) "
                f"(>= {args.older_than_days} day(s) old, "
                f"{target_size / 1024**4:.2f} TB)."
            ),
        )
        print(f"\nWrote {size / 1024:.0f} KB to {out}")
        print(f"Preview: pwsh {out} -WhatIf")
        print(f"Real:    pwsh {out}")
    else:
        print("\nUse --emit <path>.ps1 to generate a deletion script.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
